GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "testaaaaaaaa",
  "author": "aaaaaaaaaaaaa",
  "url": "adssadasdasdasdasd",
  "likes": 9
}