GET http://localhost:3003/api/blogs
###
GET http://localhost:3001/api/users
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhZmlhIiwiaWQiOiI1ZjZiNDdjNDI4NDMyODQzZTRlOWMyN2UiLCJpYXQiOjE2MDA4NzQzODJ9.2Q7Px4UhrnU_k4qLxahzbbj9XSU5rRxlDUUbqHO8gtM

{
  "title": "TestTitle1",
  "author": "Rafia B.",
  "url": "testtesttest.com",
  "likes": 1001
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "tester",
  "name": "Mister Tester",
  "password": "112233"
}
###
POST http://localhost:3003/api/logins
Content-Type: application/json

{
  "username": "tester",
  "password": "Password"
}
###
DELETE http://localhost:3003/api/blogs/BLOGIDHERE
Authorization: bearer 
###
PUT http://localhost:3003/api/blogs/BLOGIDHERE
Content-Type: application/json

{
  "title": "TestTitle",
  "author": "Rafia B.",
  "url": "testtesttest.com",
  "likes": 10
}
