GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Writers' Block? Deal With It!",
  "author": "Rafia Bushra",
  "url": "https://rafiabee.blogspot.com/",
  "likes": 0
}