get http://localhost:3001/info
###
GET http://localhost:3001/api/people
###
GET http://localhost:3001/api/people/5f60c9dd4ec51a3de873f0ba
###
POSt http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Rafia",
    "number": "1111111"
}
### 
DELETE http://localhost:3001/api/people/5f60c9dd4ec51a3de873f0ba
###
PUT http://localhost:3001/api/people/5f60c9c94ec51a3de873f0b9
Content-Type: application/json

{
    "name": "Rafia B",
    "number": "00000000"
}